version: '3'

services:
    php:
        build: ./docker/${PHP_VERSION}
        container_name: ${DOCKER_NAME}_php
        volumes:
            - ./:/var/www
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        ports:
            - '9000:9000'
        links:
            - db

    nginx:
        build: ./docker/nginx
        container_name: ${DOCKER_NAME}_nginx
        volumes:
            - ./:/var/www:ro
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - '80:80'
        links:
            - php

    db:
        build: ./docker/${DB_CONNECTION}
        container_name: ${DOCKER_NAME}_db
        volumes:
            - ./data/db:/var/lib/${DB_CONNECTION}
            - ./:/var/www
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
