version: '3'

services:
    php:
        build: ./${PHP_VERSION}
        container_name: ${PROJECT}_php
        volumes:
            - ./www/${PROJECT}:/var/www/default
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        ports:
            - '9000:9000'
        links:
            - db
        restart: always

    nginx:
        build: ./nginx
        container_name: ${PROJECT}_nginx
        volumes:
            - ./www/${PROJECT}:/var/www/default
        ports:
            - '80:80'
            - '443:443'
        links:
            - php
        restart: always

    db:
        build: ./mysql
        container_name: ${PROJECT}_db
        volumes:
            - ${MYSQL_PATH}:/var/lib/mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: mysqld --sql-mode=""
        restart: always
