version: '3'

services:
    php:
        build: ./docker/${PHP_VERSION}
        container_name: ${DOCKER_NAME}_php
        volumes:
            - ./:/var/www
            # - ./logs/php:/var/log/php:ro
            # Use for debug config:
            # - ./docker/php/conf.d:/etc/php/7.4/fpm/conf.d
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        ports:
            - "9000:9000"
            - "25:25"
        links:
            - db
        extra_hosts:
            - ${APP_DOMAIN}:${NETWORK_INTERFACE}
        networks:
            - dockernet

    nginx:
        build: ./docker/nginx
        container_name: ${DOCKER_NAME}_nginx
        volumes:
            - ./:/var/www:ro
            # - ./logs/nginx:/var/log/nginx:ro
            # Use for debug config:
            # - ./docker/nginx/conf.d:/etc/nginx/conf.d
        environment:
            APP_DOMAIN: ${APP_DOMAIN}
        ports:
            - "80:80"
        links:
            - php
        networks:
            dockernet:
                ipv4_address: ${NETWORK_INTERFACE}

    db:
        build: ./docker/${DB_VERSION}
        container_name: ${DOCKER_NAME}_db
        volumes:
            - ./docker/data/db:/var/lib/${DB_CONNECTION}
            - ./:/var/www
            # - ./logs/mysql:/var/log/mysql
        ports:
            - "${DB_PORT}:${DB_PORT}"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        networks:
            - dockernet

    mailhog:
        image: mailhog/mailhog
        container_name: ${DOCKER_NAME}_mailhog
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - dockernet

networks:
    dockernet:
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}