version: '3'

services:
    php:
        build: ./docker/${PHP_VERSION}
        container_name: ${DOCKER_NAME}_php
        volumes:
            - ./:/var/www
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        ports:
            - '9000:9000'
        links:
            - db
        restart: always

    nginx:
        build: ./docker/nginx
        container_name: ${DOCKER_NAME}_nginx
        volumes:
            - ./:/var/www:ro
        ports:
            - '80:80'
            - '443:443'
        links:
            - php
        restart: always

    db:
        build: ./docker/{DB_CONNECTION}
        container_name: ${DOCKER_NAME}_db
        volumes:
            - ${DB_PATH}:/var/lib/mysql
            - ./:/var/www:ro
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        command: mysqld --sql-mode=""
        restart: always
